version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'Drello'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    container_name: drello_db
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    image: drglasdou/drello:0.0.2
    container_name: drello_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_PASSWORD: 'password'
      DB_NAME: 'Drello'
      DB_PORT: '5432'
      DB_HOST: db
      DB_USERNAME: 'postgres'
      PORT: '3000'
      STATE: 'dev'
      JWT_SECRET: 'VQZ8cmf8naf_cwd.ukb'
