version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: drello_db
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    image: drglasdou/drello:0.0.1
    container_name: drello_backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
